apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kwasm-operator.fullname" . }}
  labels:
    {{- include "kwasm-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kwasm-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kwasm-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kwasm-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: CONTROLLER_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: AUTO_PROVISION_NODES
            value: {{ .Values.kwasmOperator.autoProvision | quote }}
          - name: INSTALLER_IMAGE
            value: {{ printf "%s/%s:%s" .Values.global.azure.images.kwasmOperatorInstallerImage.registry .Values.global.azure.images.kwasmOperatorInstallerImage.image .Values.global.azure.images.kwasmOperatorInstallerImage.tag }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s/%s:%s" .Values.global.azure.images.kwasmOperator.registry .Values.global.azure.images.kwasmOperator.image .Values.global.azure.images.kwasmOperator.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
