name: Marketplace Verify

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  verify:
    name: Verify the marketplace bundle
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/container-package-app:1.3.8
    steps:
      - uses: actions/checkout@v3

      - name: verify
        run: |
          cd marketplace
          cpa verify

  arm-ttk:
    name: Test marketplace templates
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: install arm-ttk
        run: |
          curl -sSLo arm-ttk.zip https://github.com/Azure/arm-ttk/releases/download/20240328/arm-ttk.zip
          unzip arm-ttk.zip

      - name: test marketplace package
        shell: pwsh
        run: |
          Set-Location arm-ttk/arm-ttk
          Import-Module ./arm-ttk.psd1
          Test-AzMarketplacePackage -TemplatePath ../../marketplace
